# 공통 설정 - 모든 환경에서 공통으로 사용되는 설정만
spring:
  profiles:
    active: dev  # 기본 프로파일 설정
  application:
    name: record-service
  
  # JPA 공통 설정
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect  # PostgreSQL 방언

# JWT 설정 (공통)
jwt:
  jwt-secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}  # JWT 서명 키 (환경변수 사용 권장)
  jwt-expiration-in-ms: 86400000  # 24시간

# CORS 기본 설정 (공통)
cors:
  allowedOrigins:
    - http://localhost:8080
  allowedMethods:
    - GET
    - POST
    - PUT
    - PATCH
    - DELETE
    - OPTIONS
  allowedHeaders: "*"
  allowCredentials: true

# Swagger 공통 설정
springdoc:
  packages-to-scan: com.example.recordservice.controller  # API 문서화할 패키지
  show-actuator: false  # Actuator 엔드포인트 비활성화
  default-consumes-media-type: application/json
  default-produces-media-type: application/json